spring:
  profiles:
    active: ${PROFILE}

  servlet:
    multipart:
      max-file-size: 1MB  # default 값
      max-request-size: 1MB

  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
    allowed-methods: ${ALLOWED_METHODS}

  cookie:
    max-age: ${COOKIE_MAX_AGE}
    path: ${COOKIE_PATH}
    http-only: ${COOKIE_HTTP_ONLY}
    secure: ${COOKIE_SECURE}

jwt:
  secret-key: ${SECRET_KEY}
  access-exp: ${ACCESS_EXPIRED_TIME}
  refresh-exp: ${REFRESH_EXPIRED_TIME}

cloud:
  aws:
    s3:
      bucket-name: ${S3_BUCKET_NAME}
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
      region: ${S3_REGION}
      image-url: https://${S3_BUCKET_NAME}.s3.${S3_REGION}.amazonaws.com/
